console.log( )
console.log("Cocinar una torta marmolada")
console.log( )
console.log("Ingredientes")
console.log(" ")
    console.log("-harina")
    console.log("-3 huevos")
    console.log("-1/2 kg de azucar")
    console.log("-1 taza de chocolate en polvo ")
    console.log("-1 L de leche")
    console.log("     ")
            console.log("Pasos de preparado")
        console.log("   ")
console.log("En un bols mezclar los huevos con azucar") 
console.log("luego mezclar la leche con los huevos")
console.log("agregar de a poco harina y batir ")
console.log("separar la mitad del contenido ")
console.log("a la mitad agregar el chocolate")
console.log("luego en un recipiente para hornear poner toda la masa realizada")
console.log("precalentar el horno 5 min")
console.log("hornear la torta 30 min")
console.log("retirar del horno")